### ISSUE TITLE
Migrate Dronefly to Red-DiscordBot 3.5 / discord.py 2.0

### ISSUE THREAD

**Issue by synrg** [dronefly-garden/dronefly-bots#1]
## Other instances of Dronefly on dpy2:

- CuckooBee
    - dev instance
- SeedWasp
    - test instance

## Cogs not yet ready upstream

- `fifo`
  - currently uninstalled. but if my PR is accepted, we'll be able to install from upstream
- `firstmessage`
  - currently uninstalled. but if my PR is accepted, we'll be able to install from upstream

**Comment by synrg** [comment]
One thing I'm playing with right now is using a local branch of Red with patches for the things that matter for our bots. This allows me to experiment with cogs from other Red cog developers, as well as work on new code for Dronefly.

An example of how this helps is Trusty has a lot of cogs we use, and he has dpy2 versions on his own branch, but that branch is unreleased and deliberately has a minimum 3.5.0 version set on it, so anyone trying out 3.5.0.dev1 on it can't load those cogs. However, by modifying the version# on my local Red branch, I'm able to try out those things early (but am on my own for support).

Cogs to try from Trusty's dpy2 branch:

- `extendedmodlog`
- `retrigger`
- `serverstats`
- `welcome`
- `weather`

Therefore, once I can confirm by testing each on CuckooBee, I'll load any of them that work onto SeedWasp (switching it, too, over to my local Red branch). Then I'll move on to the next repo, etc.

**Comment by synrg** [comment]
All of Trusty's dpy2 cogs now work. See updates to README.md.

**Comment by synrg** [comment]
Removed commandstats from cogs with issues, as it is now fixed. Thanks, flare!

**Comment by synrg** [comment]
Removed ebirdcog, fifo, firstmessage from cogs with issues, as ebirdcog is fixed, and fifo and firstmessage are now from https://github.com/synrg/Fox-V3/tree/dpy2.

**Comment by synrg** [comment]
Fix for rssnotifier in https://github.com/synrg/JackCogs/tree/dpy2 currently being tested.

**Comment by synrg** [comment]
Fifo still has issues:

```py
[2023-03-08 05:00:00] [DEBUG] red.fox_v3.fifo.scheduler: Looking for jobs to run
[2023-03-08 05:00:00] [DEBUG] red.fox_v3.fifo.scheduler: Next wakeup is due at 2023-03-09 05:00:00-04:00 (in 86399.904836 seconds)
[2023-03-08 05:00:00] [INFO] apscheduler.executors.default: Running job "hybrids (trigger: cron[month='*', day='*', day_of_week='*', hour='5', minute='0'], next run at: 2023-03-09 05:00:00 AST)" (scheduled at
2023-03-08 05:00:00-04:00)
[2023-03-08 05:00:00] [INFO] red.fox_v3.fifo: Executing hybrids
[2023-03-08 05:00:00] [ERROR] apscheduler.executors.default: Job "hybrids (trigger: cron[month='*', day='*', day_of_week='*', hour='5', minute='0'], next run at: 2023-03-09 05:00:00 AST)" raised an exception
Traceback (most recent call last):
  File "/home/synrg/.local/share/Red-DiscordBot/data/CuckooBee/cogs/Downloader/lib/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/home/synrg/work/Fox-V3/fifo/fifo.py", line 30, in _execute_task
    return await task.execute()
  File "/home/synrg/work/Fox-V3/fifo/task.py", line 415, in execute
    message.process_the_rest(author=author, channel=channel, content=new_content)
  File "/home/synrg/work/Fox-V3/fifo/task.py", line 137, in process_the_rest
    self._rebind_channel_reference(channel)
AttributeError: 'FakeMessage' object has no attribute '_rebind_channel_reference'
```

**Comment by synrg** [comment]
I did some work on fifo + firstmessage, reworking my former patch to make then work with dpy2 into a backwards-compatible PR upstream should be able to merge into master: https://github.com/bobloy/Fox-V3/pull/211

**Comment by synrg** [comment]
`rssnotifier` is now installed from Jack's default branch, `v3`. that just leaves Bobloy's cogs to switch over to his default branch once he merges his dpy2 stuff.

**Comment by synrg** [comment]
The migration is complete, even though there are some administrative tasks left to switch a couple of cogs over to release versions once they are released, so closing this issue.
